site_name: CitrixIndia
nav:
 - Introduction : 'index.md'
 - Overview: 'overview.md'
 - Getting Started : 'getting-started.md'
 - Using : 'using.md'
 - Using HTTP: 'using-http.md'
 - Citrix Hypervisor Management API Extensions: 'xs-api-extensions.md'
 - XenCenter API Extension : 'xc-api-extensions.md'
theme:
  name: 'readthedocs'
  prev_next_buttons_location: 'none'
